apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/deployment.yaml
images:
- name: PROJECT/IMAGE
  newName: mluukkai/pock
  newTag: 0007087cd38042db73ad989a9edfa5bae7a6c519
