name: Deploy application

on:
  push:

env:
  GKE_CLUSTER: dwk-clster
  GKE_ZONE: europe-north1-b
  BE_IMAGE: todo-backend
  APP_IMAGE: todo-app
  BRDC_IMAGE: todo-broadcaster
  CRON_IMAGE: todo-cron
  BACKUP_IMAGE: backup-cron
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and publish backend
        run: |-
          docker build --tag "mluukkai/pock-$GITHUB_SHA" .
  