name: do something

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: create a file with random content
      run: echo $RANDOM > random.txt
    - uses: EndBug/add-and-commit@v9
      with:
        add: 'random.txt'
        message: New version release for gitops-app ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: daily-contribution
        # Set the Git credentials - replace this with your own secrets
        github_token: ${{ secrets.GH_TOKEN }}